apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: dev-

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 4096M
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud/userData
        value: |-
          #cloud-config
          user: fedora
          password: fedora
          chpasswd: { expire: False }
          package_upgrade: true
          packages:
            - httpd
            - gcc
          runcmd:
            - systemctl enable httpd
            - systemctl start httpd
    target:
      kind: VirtualMachine
